name: Build Release

on:
  workflow_dispatch:
  schedule:
    # Scheduled Daily (Midnight)
    - cron: "0 0 * * *"

env:
  SKIP_BUILD: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Inkscape, XVFB and GitHub CLI
        run: |
          sudo add-apt-repository ppa:inkscape.dev/stable
          sudo apt-get install -y inkscape xvfb gh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install Node / NPM
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install Pipx, Poetry and dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry
          poetry config virtualenvs.in-project true
          poetry install
          npm install

      - name: Build Project and Commit Changes
        run: |
          git pull --tags
          poetry run vectors build .
          git add .
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m "deps(build): Process daily updates." || { echo "No changes to commit, skipping build process."; echo "SKIP_BUILD=true" >> $GITHUB_ENV; exit 0; }
          git push || { echo "No changes to push, skipping build process.";  echo "SKIP_BUILD=true" >> $GITHUB_ENV; exit 0; }
          poetry run cz -nr 21,16,7 bump --yes
          git push && git push --tags

      - name: Generate Release Tag
        id: generate_tag
        if: ${{ env.SKIP_BUILD != 'true' }}
        run: |
          echo "NOW=$(date -u +'%Y-%m-%d %H:%M:%S') UTC" >> $GITHUB_ENV
          echo "NOW_PATH=$(date -u +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ env.SKIP_BUILD != 'true' }}
        with:
          name: ${{ env.NOW }}
          files: mtg-vectors.optimized.zip
          tag_name: ${{ env.NOW_PATH }}
          fail_on_unmatched_files: true
          body: "This is an automated release that ingests changes to the SVG catalog and live Scryfall data."

      - name: Delete old releases
        run: gh release list --json tagName --jq '.[] | .tagName' | tail -n+7 | xargs -r -n 1 gh release delete --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
